### ISSUE TITLE
Application configuration using a config file

### ISSUE THREAD

**Issue by Nic822** [rursprung/fhgr-sweng-pattern-recognition#9]

**Comment by rursprung** [comment]
there are multiple options to do this. one is to use a INI-type config file and [`configparser`](https://docs.python.org/3/library/configparser.html) ,the other is to use a more modern TOML file and [`tomllib`](https://docs.python.org/3/library/tomllib.html).
i wouldn't use JSON with the [`json`](https://docs.python.org/3/library/json.html) library as JSONs are not particularly well suited for config files (e.g. no comments unless you use [JSON5](https://json5.org/)).
